### ISSUE TITLE
Does it support nested directories with images?

### ISSUE THREAD

**Issue by inlinwei** [jefferyhe/image-tagger#1]

**Comment by jefferyhe** [comment]
Thanks for the report! It doesn't support nested directories right now. I'll fix it soon!

**Comment by tolinwei** [comment]
@jefferyhe Thanks, this is somewhat important for me since i'm using Lightroom for indexing and post-processing my photos, the images would be imported in the structure by either dates or topics, it would be quite convenient if I can just denote a top level folder for tagging.

**Comment by jefferyhe** [comment]
@tolinwei  Fixed! Now it will automatically process all the subfolders for given directory.
Thank you so much for the feedback! You're right, recursively process subfolders is an very important feature for this project. Please feel free to make more comments.
